trigger:
- main

pool:
  vmImage: windows-2019

steps:
- task: VSBuild@1
  inputs:
    solution: '**\HSPI_ZWaveParameters.sln'
    vsVersion: '16.0'
    platform: 'Any CPU'
    configuration: 'Release'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
 