name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
   
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore HSPI_ZWaveParameters.sln

      - name: Build Solution
        run: |
          msbuild.exe HSPI_ZWaveParameters.sln /p:platform="Any CPU" /p:configuration="Release"
          
      - name: Unit Tests
        run: |
          mtests.exe tests\bin\Release\HSPI_ZWaveParametersTest.dll /resultsfile:TestResults.trx

