name: 'Unit Test Report'

on:
  workflow_run:
    workflows: ['Build and Test']                     # runs after CI workflow
    types:
      - completed

jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
    - name: Publish results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Unit Tests                  # Name of the check run which will be created
        path: '*.trx'
        reporter: dotnet-trx              # Format of test results
