name: Code analysis
on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    SONAR_SCANNER_DOWNLOAD_URL: "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.4.0.40033/sonar-scanner-msbuild-5.4.0.40033-net46.zip"
    SONAR_SCANNER_VERSION : "5.4.0"
    SLN_FILE: "HSPI_ZWaveParameters.sln"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Set up JDK 11 for Sonarcloud
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
   
      - name: Cache Nuget Packages
        uses: actions/cache@v2
        with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
         restore-keys: |
              ${{ runner.os }}-nuget-

      - name: Download and set up sonar-scanner
        run: |
          New-Item -Force -ItemType directory -Path $HOME\.sonar
          curl -sSLo $HOME\.sonar\sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }}
          unzip -o $HOME\.sonar\sonar-scanner.zip -d $HOME\.sonar\

      - name: Restore Nuget Packages
        run: nuget restore $SLN_FILE

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dir $HOME\.sonar
          $HOME\.sonar\SonarScanner.MSBuild.exe begin /k:"dk307_HSPI_ZWaveParameters" /o:"dk307" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          cd $GITHUB_WORKSPACE
          msbuild.exe SLN_FILE /p:platform="Any CPU" /p:configuration="Debug"
          $HOME\.sonar\scanner\SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"