name: 'Unit Tests On Windows'

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
   
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore HSPI_ZWaveParameters.sln

      - name: Build Solution
        run: msbuild.exe HSPI_ZWaveParameters.sln /p:platform="Any CPU" /p:configuration="Debug"
          
      - name: Unit tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: tests\HSPI_ZWaveParametersTest.csproj
          report_name: windows_unit_tests
          report_title: Windows Unit Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: window_unit_tests.md
          gist_badge_label: 'Windows Unit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}  